# Generated by Django 5.2.8 on 2025-12-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='進化段階')),
            ],
        ),
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='わざの属性名')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='特徴')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='属性名')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カード名称')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='所持枚数')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像ファイルパス')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('evolution_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.evolutionstage', verbose_name='進化段階')),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.pokemoncard', verbose_name='進化元カード')),
                ('move_types', models.ManyToManyField(blank=True, to='cards.movetype', verbose_name='わざの属性')),
                ('special_features', models.ManyToManyField(blank=True, to='cards.specialfeature', verbose_name='特徴')),
                ('types', models.ManyToManyField(blank=True, to='cards.type', verbose_name='タイプ')),
            ],
        ),
    ]
