# Generated by Django 5.2.8 on 2025-12-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolutionstage',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='evolutionstage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='types',
            field=models.ManyToManyField(to='cards.type', verbose_name='タイプ'),
        ),
    ]
