# Generated by Django 5.2.8 on 2025-12-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_evolutionstage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movetype',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='specialfeature',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='movetype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='specialfeature',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='type',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='movetype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='わざのエネルギータイプ'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='move_types',
            field=models.ManyToManyField(blank=True, to='cards.movetype', verbose_name='わざのエネルギータイプ'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='special_features',
            field=models.ManyToManyField(blank=True, to='cards.specialfeature', verbose_name='特別'),
        ),
        migrations.AlterField(
            model_name='specialfeature',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='特別'),
        ),
    ]
