# Generated by Django 5.2.8 on 2025-12-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_movetype_options_alter_specialfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncard',
            name='image_path',
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='画像'),
        ),
    ]
