# Generated by Django 5.2.8 on 2025-12-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_pokemoncard_image_path_pokemoncard_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemoncard',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='evolves_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='進化元カード'),
        ),
    ]
