# Generated by Django 5.2.8 on 2025-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_pokemoncard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movetype',
            name='bg_color',
            field=models.CharField(default='#6b7280', help_text='例: #ff0000', max_length=7, verbose_name='背景色'),
        ),
        migrations.AddField(
            model_name='movetype',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='例: #000000', max_length=7, verbose_name='文字色'),
        ),
        migrations.AddField(
            model_name='type',
            name='bg_color',
            field=models.CharField(default='#6b7280', help_text='例: #ff0000', max_length=7, verbose_name='背景色'),
        ),
        migrations.AddField(
            model_name='type',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='例: #000000', max_length=7, verbose_name='文字色'),
        ),
    ]
