# Generated by Django 5.2.8 on 2025-12-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_movetype_bg_color_movetype_text_color_type_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='evolution_stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cards.evolutionstage', verbose_name='進化段階'),
        ),
    ]
