# Generated by Django 5.2.8 on 2025-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_pokemoncard_evolution_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(unique=True, verbose_name='URL用スラッグ')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('bg_color', models.CharField(default='#6b7280', help_text='例: #ff0000', max_length=7, verbose_name='背景色')),
                ('text_color', models.CharField(default='#ffffff', help_text='例: #000000', max_length=7, verbose_name='文字色')),
            ],
            options={
                'verbose_name': 'カードカテゴリ',
                'verbose_name_plural': 'カードカテゴリ',
                'ordering': ['display_order'],
            },
        ),
    ]
