# Generated by Django 5.2.8 on 2025-12-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='特別な分類')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('bg_color', models.CharField(default='#6b7280', help_text='例: #ff0000', max_length=7, verbose_name='背景色')),
                ('text_color', models.CharField(default='#ffffff', help_text='例: #000000', max_length=7, verbose_name='文字色')),
            ],
            options={
                'verbose_name': '特別な分類',
                'verbose_name_plural': '特別な分類',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TrainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='トレーナーズ種別')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'トレーナーズ種別',
                'verbose_name_plural': 'トレーナーズ種別',
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='movetype',
            options={'ordering': ['display_order'], 'verbose_name': 'わざのエネルギータイプ', 'verbose_name_plural': 'わざのエネルギータイプ'},
        ),
    ]
