# Generated by Django 5.2.8 on 2025-12-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_trainertype_bg_color_trainertype_text_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemoncard',
            options={'ordering': ['name'], 'verbose_name': 'カード', 'verbose_name_plural': 'カード'},
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='category',
            field=models.ForeignKey(default=1, help_text='ポケモンまたはトレーナーズ', on_delete=django.db.models.deletion.PROTECT, to='cards.cardcategory', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='special_trainers',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.specialtrainer', verbose_name='特別な分類'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='trainer_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.trainertype', verbose_name='トレーナーズ種別'),
        ),
        migrations.AlterField(
            model_name='movetype',
            name='text_color',
            field=models.CharField(default='#    ', help_text='例: #000000', max_length=7, verbose_name='文字色'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='evolution_stage',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.evolutionstage', verbose_name='進化段階'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='types',
            field=models.ManyToManyField(blank=True, to='cards.type', verbose_name='タイプ'),
        ),
    ]
