# Generated by Django 5.2.8 on 2025-12-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_pokemoncard_options_pokemoncard_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movetype',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='例: #000000', max_length=7, verbose_name='文字色'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='evolution_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.evolutionstage', verbose_name='進化段階'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='trainer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.trainertype', verbose_name='トレーナーズ種別'),
        ),
    ]
