# Generated by Django 5.2.8 on 2025-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_movetype_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='所持枚数'),
        ),
    ]
