# Generated by Django 5.2.8 on 2025-12-19 06:18

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_alter_pokemoncard_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models.card_image_upload_to, verbose_name='画像'),
        ),
    ]
