# Generated by Django 5.2.8 on 2025-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_pokemoncard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='HP'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='resistance',
            field=models.ManyToManyField(blank=True, related_name='resistance_cards', to='cards.type', verbose_name='抵抗力'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='retreat_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='にげる'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='weakness',
            field=models.ManyToManyField(blank=True, related_name='weakness_cards', to='cards.type', verbose_name='弱点'),
        ),
    ]
