# Generated by Django 5.2.8 on 2025-12-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_pokemoncard_hp_pokemoncard_resistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='retreat_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='にげるエネルギー'),
        ),
    ]
