# Generated by Django 5.2.8 on 2025-12-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_pokemoncard_retreat_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiApiKeyUsage',
            fields=[
                ('key_index', models.IntegerField(help_text='0-8の範囲（GEMINI_API_KEY_1～9に対応）', primary_key=True, serialize=False, verbose_name='API KEYインデックス')),
                ('usage_count', models.IntegerField(default=0, verbose_name='本日の使用回数')),
                ('last_reset_date', models.DateField(auto_now_add=True, verbose_name='最終リセット日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': 'Gemini API KEY使用状況',
                'verbose_name_plural': 'Gemini API KEY使用状況',
                'db_table': 'gemini_api_key_usage',
            },
        ),
    ]
